/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminTeachersRouteImport } from './routes/admin/teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminSiteRouteImport } from './routes/admin/site'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPoliciesRouteImport } from './routes/admin/policies'
import { Route as AdminLessonsRouteImport } from './routes/admin/lessons'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'
import { Route as AdminContactRouteImport } from './routes/admin/contact'
import { Route as AdminCatalogRouteImport } from './routes/admin/catalog'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/enroll': typeof EnrollRoute
  '/faq': typeof FaqRoute
  '/policies': typeof PoliciesRoute
  '/pricing': typeof PricingRoute
  '/programs': typeof ProgramsRoute
  '/teachers': typeof TeachersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/enroll': typeof EnrollRoute
  '/faq': typeof FaqRoute
  '/policies': typeof PoliciesRoute
  '/pricing': typeof PricingRoute
  '/programs': typeof ProgramsRoute
  '/teachers': typeof TeachersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/enroll': typeof EnrollRoute
  '/faq': typeof FaqRoute
  '/policies': typeof PoliciesRoute
  '/pricing': typeof PricingRoute
  '/programs': typeof ProgramsRoute
  '/teachers': typeof TeachersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/courses'
    | '/enroll'
    | '/faq'
    | '/policies'
    | '/pricing'
    | '/programs'
    | '/teachers'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/contact'
    | '/admin/faqs'
    | '/admin/lessons'
    | '/admin/policies'
    | '/admin/settings'
    | '/admin/site'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/enroll'
    | '/faq'
    | '/policies'
    | '/pricing'
    | '/programs'
    | '/teachers'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/contact'
    | '/admin/faqs'
    | '/admin/lessons'
    | '/admin/policies'
    | '/admin/settings'
    | '/admin/site'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/testimonials'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/courses'
    | '/enroll'
    | '/faq'
    | '/policies'
    | '/pricing'
    | '/programs'
    | '/teachers'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/contact'
    | '/admin/faqs'
    | '/admin/lessons'
    | '/admin/policies'
    | '/admin/settings'
    | '/admin/site'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  EnrollRoute: typeof EnrollRoute
  FaqRoute: typeof FaqRoute
  PoliciesRoute: typeof PoliciesRoute
  PricingRoute: typeof PricingRoute
  ProgramsRoute: typeof ProgramsRoute
  TeachersRoute: typeof TeachersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminContactRoute: AdminContactRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  EnrollRoute: EnrollRoute,
  FaqRoute: FaqRoute,
  PoliciesRoute: PoliciesRoute,
  PricingRoute: PricingRoute,
  ProgramsRoute: ProgramsRoute,
  TeachersRoute: TeachersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
